import { Router, Request, Response } from "express";
import { db } from "../storage";
import { organizations, processes, processSteps, users, userOrganizations } from "../../shared/schema";
import { eq, and } from "drizzle-orm";
import { supabaseAdmin } from "../supabase";

// Need to duplicate logic since we can't import client-side code directly in Node if it uses React types
// For now, we'll trust the client sends the nodes, OR we re-generate here.
// Best practice: Trust client for the *Edited* nodes, since user might have changed them.

const router = Router();

async function getOrgId(req: Request): Promise<string | null> {
    const authHeader = req.headers.authorization;
    if (!authHeader) return null;
    const token = authHeader.replace("Bearer ", "");
    const { data: { user }, error } = await supabaseAdmin.auth.getUser(token);
    if (error || !user) return null;
    const userOrg = await db.query.userOrganizations.findFirst({ where: eq(userOrganizations.userId, user.id) });
    return userOrg ? userOrg.organizationId : null;
}

router.post("/complete", async (req: Request, res: Response) => {
    try {
        const organizationId = await getOrgId(req);
        if (!organizationId) return res.status(401).json({ message: "Unauthorized" });

        const { industry, nodes, edges } = req.body;

        if (!industry) return res.status(400).json({ message: "Industry is required" });

        // 1. Update Organization Profile
        await db.update(organizations)
            .set({
                industry: industry.toLowerCase().includes('logistica') ? 'logistics' : 'other', // Mapping simplified for demo
                onboardingStatus: 'completed',
                meta: {
                    raw_industry: industry,
                    ai_context: `User defined industry as ${industry}`
                }
            })
            .where(eq(organizations.id, organizationId));

        // 2. Create the Main Process
        const [proc] = await db.insert(processes).values({
            organizationId,
            name: `Proceso Principal - ${industry}`,
            type: 'production', // Generic for now
            description: `Generated by Nexus Architect for ${industry}`,
            isTemplate: false
        }).returning();

        // 3. Create Steps from Nodes
        // We assume 'nodes' is an array of ReactFlow nodes
        if (nodes && Array.isArray(nodes)) {
            // Sort by Y position to roughly determine order
            const sortedNodes = nodes.sort((a: any, b: any) => a.position.y - b.position.y);

            for (let i = 0; i < sortedNodes.length; i++) {
                const node = sortedNodes[i];
                await db.insert(processSteps).values({
                    processId: proc.id,
                    name: node.data.label,
                    type: node.type === 'input' ? 'task' : node.type === 'output' ? 'milestone' : 'task',
                    order: i + 1,
                    expectedDuration: 60, // Default 1 hour (in minutes)
                    dependencies: [], // Complex edge mapping omitted for MVP
                    criticalKpis: {} // Empty KPIs object
                });
            }
        }

        res.json({ success: true, message: "Onboarding completed", processId: proc.id });

    } catch (error) {
        console.error("Onboarding error:", error);
        res.status(500).json({ message: "Internal server error" });
    }
});

export const onboardingRoutes = router;
