INSERT INTO knowledge_base (category, title, content, tags, access_roles, metadata)
VALUES (
    'tutorial',
    'Guía de Inicio Rápido: Panel de Administración',
    E'# Guía de Inicio Rápido: Panel de Administración\n\nBienvenido al nuevo Panel de Administración del Sistema ERP + IA. Este panel centraliza la gestión de sus agentes de IA, documentación y herramientas de implementación.\n\n## **1. Navegación Principal**\n\nEl panel se divide en tres secciones principales:\n\n* **Agentes:** Visualice y monitoree el estado de sus agentes de IA activos.\n* **Documentación:** Acceda a la base de conocimientos, tutoriales y guías del sistema.\n* **Checklist Implementación:** Una herramienta interactiva para guiarle en el proceso de adopción de IA.\n\n## **2. Uso del Checklist de Implementación**\n\nLa pestaña "Checklist Implementación" contiene una hoja de ruta detallada para la transformación digital de su empresa:\n\n* **Seguimiento de Progreso:** Marque las tareas a medida que las complete. El sistema guardará su progreso automáticamente.\n* **Fases Estructuradas:** El proceso está dividido en 9 fases clave, desde la definición de objetivos hasta la mejora continua.\n* **Visualización:** La barra de progreso superior le muestra qué tan cerca está de completar la implementación.\n\n## **3. Gestión de Documentación**\n\nEn la pestaña "Documentación", puede:\n\n* **Buscar:** Utilice la barra de búsqueda para encontrar guías específicas.\n* **Filtrar:** Los documentos están categorizados para facilitar su localización.\n* **Lectura:** Seleccione cualquier documento para verlo en el panel de lectura a la derecha.\n\n## **4. Agentes de IA**\n\nMonitoree sus agentes inteligentes:\n\n* **Roles:** Identifique qué función cumple cada agente (Soporte, Ventas, Inventario).\n* **Capacidades:** Vea qué habilidades específicas tiene cada agente habilitadas.\n\n---',
    '["admin", "tutorial", "guía", "inicio rápido"]'::jsonb,
    '["admin", "manager", "user"]'::jsonb,
    '{"author": "system", "target_user": "drakengdl@gmail.com"}'::jsonb
);
